### ISSUE TITLE
Add instructions for TL866CS - I am providing an example provided for a SST39SF020A FLASH chip

### ISSUE THREAD

**Issue by magore** [Z80-Retro/Z80-Retro-Manual#13]
It may not be obvious to some  how to flash using a TL866CS from linux
So I am giving an example here using a  SST39SF020A

minipro -s -p SST39SF020A -w 2063-Z80-cpm/boot/firmware.bin
Found TL866CS 03.2.86 (0x256)
Device code: 54416913
Serial code: 58CD45F94BB765B9A1DF15A9
Chip ID: 0xBFB6  OK
Warning: Incorrect file size: 2463 (needed 262144)
Erasing... 0.40Sec OK
Writing Code...  0.19Sec  OK
Reading Code...  0.03Sec  OK
Verification OK

**Comment by linuxplayground** [comment]
Thanks for that. 

I'll add it to the manual in the currently open pull request.
