### ISSUE TITLE
Found a typo in the dev install instructions

### ISSUE THREAD

**Issue by davewill** [Z80-Retro/Z80-Retro-Manual#5]
Was running through the instructions to set up the build environment on a fresh Raspian install and ran into a problem with the command line:

**sudo apt-get install build-essentials z80asm cpmtools**

from the "Install Build Dependencies" section. 

I got the error message:

**E: Unable to locate package build-essentials**

It took a little while to realize that the package should be "build-essential" without the 's' on the end,

**Comment by linuxplayground** [comment]
Thanks for this,  if you find any more typos, please let me know in this issue.  I'll keep it open for a while... 

I'll fire up my vim and fix this one but will wait before I push a commit in case you find any more.

**Comment by linuxplayground** [comment]
I applied a spell checker to the problem.  Note: I am in New Zealand so my spelling might be different to what you are used to.  That said, If anything still looks amiss, feel free to leave a comment.
